# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='account.Skill'),
        ),
    ]
